import type { Metadata } from "next";
import { Geist, Lobster_Two } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const fontSofia = Lobster_Two({
  variable: "--font-sofia",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Zendt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${fontSofia.variable} antialiased bg-background text-foreground font-sans`}
      >
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
